COMMENT =	fast and exact implementation of from_chars for float/double

V =		6.1.0
PKGNAME =	fast-float-${V}
REVISION =	0
GH_TAGNAME =	v${V}
GH_ACCOUNT =	fastfloat
GH_PROJECT =	fast_float
DISTFILES =	fast_float-{v}${V}-0.tar.gz

CATEGORIES =	devel

MAINTAINER =	Jose Maldonado <josemald89@gmail.com>

# Apache 2.0, Boost 1.0, or MIT
PERMIT_PACKAGE =	Yes

MODULES =	devel/cmake

.include <bsd.port.mk>
